USE MASTER
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'HOTELDB')
	DROP DATABASE HOTELDB
GO

CREATE DATABASE HOTELDB
GO
USE HOTELDB
GO


CREATE TABLE TBL_USUARIOS (
	USUARIO_ID INT PRIMARY KEY IDENTITY,
	USUARIO VARCHAR(50),
	NOMBRE VARCHAR(250),
	CLAVE VARCHAR(250),
	ROL VARCHAR(50),
	EMAIL VARCHAR(150)
)

SELECT * FROM TBL_USUARIOS

CREATE TABLE TBL_CATEGORIAS_HABITACIONES (
	CATEGORIA_CODIGO VARCHAR(50) PRIMARY KEY,
	CATEGORIA_NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE TBL_HABITACIONES (
	HABITACION_CODIGO AS
	CAST(
        (CATEGORIA_CODIGO + 
         RIGHT('00' + CAST(PISO AS VARCHAR), 2) + 
         RIGHT('00' + CAST(NUMERO AS VARCHAR), 2)) PERSISTED,
	CATEGORIA_CODIGO VARCHAR(50),
	PISO INT,
	NUMERO INT,

	CAPACIDAD INT,
	PRECIO NUMERIC,

	PRIMARY KEY (HABITACION_CODIGO),
    FOREIGN KEY (CATEGORIA_CODIGO) REFERENCES TBL_CATEGORIAS_HABITACIONES(CATEGORIA_CODIGO)
)

CREATE TABLE TBL_RESERVAS (
	RESERVA_ID INT PRIMARY KEY IDENTITY(10001,1),
	HABITACION_CODIGO VARCHAR(50),
	FECHA_ENTRADA DATE,
	FECHA_SALIDA DATE,
	DIAS INT DEFAULT 0,

	DNI VARCHAR(50),
	NOMBRE_CLIENTE VARCHAR(250),
	TIPO_PAGO VARCHAR(50),
	PRECIO NUMERIC,
	TOTAL NUMERIC,

	FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
	ANULADA VARCHAR(5) DEFAULT 'N',

	FOREIGN KEY (HABITACION_CODIGO) REFERENCES TBL_HABITACIONES(HABITACION_CODIGO)
)


INSERT INTO TBL_USUARIOS (USUARIO, NOMBRE, CLAVE, ROL, EMAIL) VALUES
	('SA', 'ADMINISTRADOR', '123', 'ADMIN','didierbonilla25@gmail.com'),
	('KCOOPER', 'KENNY COOPER', '123', 'STANDARD','didierbonilla25@gmail.com')


INSERT INTO TBL_CATEGORIAS_HABITACIONES (CATEGORIA_CODIGO, CATEGORIA_NOMBRE) VALUES
	('IND', 'HABITACI�N INDIVIDUAL'),
	('DOB', 'HABITACI�N DOBLE'),
	('TRI', 'HABITACI�N TRIPLE'),
	('CUA', 'HABITACI�N CU�DRUPLE'),
	('SUI', 'SUITE'),
	('JSU', 'JUNIOR SUITE'),
	('GSU', 'GRAN SUITE'),
	('MSU', 'MASTER SUITE'),
	('MIN', 'MINI-SUITE'),
	('EST', 'HABITACI�N TIPO ESTUDIO');

INSERT INTO TBL_HABITACIONES (CATEGORIA_CODIGO, PISO, NUMERO, CAPACIDAD, PRECIO) VALUES
	('IND', 1, 1, 1, 450),
	('IND', 1, 2, 1, 450),
	('IND', 1, 3, 1, 450),
	('IND', 1, 4, 1, 450),

	('DOB', 1, 5, 2, 600),
	('DOB', 1, 6, 2, 600),
	('DOB', 1, 7, 2, 600),

	('CUA', 1, 8, 2, 1200),
	('CUA', 1, 9, 2, 1200),
	('CUA', 1, 10, 2, 1200),

	('SUI', 2, 1, 2, 1200),
	('JSU', 2, 2, 2, 1200),
	('GSU', 2, 3, 2, 1200),

	('MSU', 3, 1, 2, 1200),
	('MIN', 3, 2, 2, 1200),
	('EST', 3, 3, 2, 1200)

	
SELECT * FROM TBL_USUARIOS
SELECT * FROM TBL_CATEGORIAS_HABITACIONES
SELECT * FROM TBL_HABITACIONES